services:
    ansible:
        build:
            # https://stackoverflow.com/questions/24537340/docker-adding-a-file-from-a-parent-directory
            context: .
            dockerfile: ./ansible/Dockerfile
        command: sleep infinity
        volumes:
            - ./:/workspace
    ubuntu-1:
        build:
            context: .
            dockerfile: ./ubuntu/Dockerfile
        ports:
        - "4001:80"
    ubuntu-2:
        build:
            context: .
            dockerfile: ./ubuntu/Dockerfile
        ports:
        - "4002:80"
    ubuntu-3:
        build:
            context: .
            dockerfile: ./ubuntu/Dockerfile
        ports:
        - "4003:80"
